### ISSUE TITLE
No auto-focus on input-field - Version 40.3 (33839)

### ISSUE THREAD

**Issue by fdegenhardt** [dawidw/move-it#4]
have to click manually in one field – and no cycle with tab-key

**Comment by peternowell** [comment]
This would be very very helpful!

**Comment by vladmoroz** [comment]
Hey guys, here's a way to fix this for now
1. Open the Sketch plugin folder, right click to open MoveIt.sketchplugin package, then Contents -> Sketch

File path should look like this:
`/Users/vlad/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Move It/MoveIt.sketchplugin/Contents/Sketch`

2. Open **script.cocoascript** with a text editor, find line 54 that says `return alert` and add following code above this line

```
    var firstField = alert.viewAtIndex(1);
    var secondField = alert.viewAtIndex(3);
    alert.alert().window().setInitialFirstResponder(firstField);
    firstField.setNextKeyView(secondField);
    secondField.setNextKeyView(firstField);
```

3. Relaunch Sketch

**Comment by fdegenhardt** [comment]
Great – thx a lot!!

Fabian

> Am 28.11.2016 um 10:44 schrieb Vlad Moroz <notifications@github.com>:
> 
> .

**Comment by peternowell** [comment]
Hmm, I don't see that  script.cocoascript file—even when I look for hidden files in that directory. Is the new code included in the plugin now, if I redownload it?

**Comment by vladmoroz** [comment]
@peternowell Did you manage to open MoveIt.sketchplugin as a package?
https://www.dropbox.com/s/263ho875n6zbbdo/Screenshot%202016-11-29%2020.57.16.png?dl=0

**Comment by peternowell** [comment]
Ah... for some reason there's a folder titled MoveIt in the same directory as the MoveIt.sketchplugin file, and the filepath you gave was opening that folder when pasted into Finder's Go To function. Got it now. Should I delete that folder, btw?
Also, I teach tons of designers and want to make sure this issue is resolved in the downloadable plugin before recommending it to hundreds of students. Is that in the works? Thanks, Vlad!

**Comment by vladmoroz** [comment]
@peternowell Have no idea. I did submit a pull request with the fix.

**Comment by dawidw** [comment]
Fixed thanks to @vladmoroz
