### ISSUE TITLE
Tab key to move focus between input fields

### ISSUE THREAD

**Issue by peternowell** [dawidw/move-it#5]
Hi David, it would be so useful to be able to use the tab and shift+tab keys to move between the 2 input fields. Between this and the lack of auto-focus on the first field, the plugin is so much less efficient in a workflow. Is this possible for you to change?

**Comment by vladmoroz** [comment]
Please see my answer here:
https://github.com/dawidw/move-it/issues/4

That's a temporary fix for your issue as well

**Comment by dawidw** [comment]
Hi @peternowell 
This issue has been fixed by @vladmoroz . Please download the latest version :)
