### ISSUE TITLE
Keyboard shortcut not working in Sketch v41

### ISSUE THREAD

**Issue by peternowell** [dawidw/move-it#6]
Am I the only one that the shortcut isn't working for? I tried to manually set it in System Prefs, but it won't work—perhaps because the menu item is within a directory/menu-group with the same name.

**Comment by dawidw** [comment]
Hi @peternowell 
This is the first time I hear of this issue. Maybe one of your other plugins is bind to this combination  : <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>m</kbd> . Try to open manifest.json and change the shortcut to something you're sure none of your plugins use.
